import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <NextTopLoader color="#FE595E"/>
          {children}
      </body>
    </html>
  );
}
